#! /bin/sh
bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color "#ff0005"
bspc config presel_feedback_colors "#222222"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config top_padding 	-5
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^5'
bspc rule -a Steam desktop='^4'
