/* Terminal colors (16 first used in escape sequence) */
static const char *colorname[] = {

  /* 8 normal colors */
  [0] = "#1d1f21", /* black   */
  [1] = "#cc342b", /* red     */
  [2] = "#198844", /* green   */
  [3] = "#fba922", /* yellow  */
  [4] = "#3971ed", /* blue    */
  [5] = "#a36ac7", /* magenta */
  [6] = "#3971ed", /* cyan    */
  [7] = "#c5c8c6", /* white   */

  /* 8 bright colors */
  [8]  = "#969896", /* black   */
  [9]  = "#cc342b", /* red     */
  [10] = "#198844", /* green   */
  [11] = "#fba922", /* yellow  */
  [12] = "#3971ed", /* blue    */
  [13] = "#a36ac7", /* magenta */
  [14] = "#3971ed", /* cyan    */
  [15] = "#ffffff", /* white   */
